# Generated by Django 5.2.5 on 2025-08-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(help_text='Nome do Pet (máximo de 10 caracteres)', max_length=10)),
                ('historia_pet', models.TextField(default='História do Pet não fornecida')),
                ('status', models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], default='P', max_length=1)),
                ('especie', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], max_length=10)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('tamanho', models.CharField(choices=[('Grande', 'Grande'), ('Médio', 'Médio'), ('Pequeno', 'Pequeno')], max_length=10)),
                ('cuidados', models.JSONField(blank=True, default=list)),
                ('vive_bem_em', models.JSONField(blank=True, default=list)),
                ('temperamento', models.JSONField(blank=True, default=list)),
                ('sociavel_com', models.JSONField(blank=True, default=list)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/secondary/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='divulgar.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='fotos_secundarias',
            field=models.ManyToManyField(blank=True, related_name='secondary_images', to='divulgar.petimage'),
        ),
    ]
