# Generated by Django 5.2.5 on 2025-08-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_interessado', models.CharField(max_length=100)),
                ('email_interessado', models.EmailField(max_length=254)),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='divulgar.pet')),
            ],
        ),
    ]
