# Generated by Django 5.2.5 on 2025-08-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_interesseadocao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteresseAdocao',
        ),
    ]
